### ISSUE TITLE
Preloads

### ISSUE THREAD

**Issue by fanatid** [jprichardson/bitcoin-faucet#1]
Are you planning implement preloads? like in [helloblock](https://helloblock.io/docs/ref#faucet-single)

**Comment by jprichardson** [comment]
I wasn't planning on it, although it'd be super easy to implement. What
would the use case be?

On Friday, May 8, 2015, Kirill Fomichev notifications@github.com wrote:

> Are you planning implement preloads? like in helloblock
> https://helloblock.io/docs/ref#faucet-single
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jprichardson/bitcoin-faucet/issues/1.

## 

Simple & Secure Bitcoin Wallet: https://www.coinbolt.com
Bitcoin / JavaScript: http://cryptocoinjs.com
Follow JP Richardson on Twitter: https://twitter.com/jprichardson

**Comment by fanatid** [comment]
Probably it would be helpful for developers who want generate and send transactions in their tests. Of course they can use withdrawal, but if they send Tx2 that use output Tx1 (withdrawal transaction) not to insight (now you use this provider) before their provider receive Tx1 they get error. If they use preloads it's mean that Tx1 already confirmed and include to insight and developer provider, in this case error will be raised only if Tx2 invalid.

**Comment by jprichardson** [comment]
> Probably it would be helpful for developers who want generate and send transactions in their tests.

You can already do this. You just have to generate the address. The reference implementation allows sending transactions with inputs that are still unconfirmed. 

Having preloads that are already confirmed? That complicates the design and is something I probably won't do until I find a case where I really need it.

**Comment by fanatid** [comment]
Oh, I don't know that reference implementation allows this...
Thanks for explanation and for the faucet!

**Comment by fanatid** [comment]
@jprichardson FYI, I finally finished my own faucet with preloads https://github.com/fanatid/bitcoin-faucet-api It required 8 months :laughing: 
I made this because when I used withdrawal from http://blocktrail.com/ and send new transaction to http://test-insight.bitpay.com/ I was received `Missing inputs`

**Comment by jprichardson** [comment]
Nicely done!
